server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://discovery:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
