server:
  port: 8888

eureka:
  instance:
    hostname: config-server
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/undancer/cloud-config-repo.git